config/routes.rb
Rails.application.routes.draw do
  get :results, to: 'pages#results'
  resources :cities, only: :show do
    collection do
      get :search
    end
    member do
      get :data
    end
  end
  get :select_stations, to: 'pages#select_stations'
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  self.primary_key = :service_id
end

app/models/station.rb
class Station < ApplicationRecord
end

app/models/stop.rb
class Stop < ApplicationRecord
  self.primary_key = :stop_id
  # default_scope { where(location_type: 0).where("stop_id LIKE 'StopPoint:OCETrain%'") }

  geocoded_by :address, :latitude  => :stop_lat, :longitude => :stop_lon

  has_many :stop_times


  def self.get_many_stats_schedule(stop_from_ids, target_stop_ids, start_time, end_time)
    sql = "

      SELECT  stops.stop_id,
              stops.stop_name as gare_start,
              stop_times_main.departure_time::time as start_time,
              stops_lyon.stop_name as gare_end,
              stop_times_lyon.arrival_time::time as end_time,
              stop_times_main.trip_id,
              trips.service_id,
              calendars.monday
      FROM stops
      INNER JOIN stop_times as stop_times_main ON stop_times_main.stop_id = stops.stop_id
      INNER JOIN stop_times as stop_times_lyon ON stop_times_main.trip_id = stop_times_lyon.trip_id
      INNER JOIN stops as stops_lyon ON stop_times_lyon.stop_id = stops_lyon.stop_id
      INNER JOIN trips ON stop_times_main.trip_id = trips.trip_id
      INNER JOIN calendars ON calendars.service_id = trips.service_id
      WHERE stops.stop_id IN (#{stop_from_ids.map{|s| "'#{s}'"}.join(',')})
        AND (stop_times_main.departure_time::time BETWEEN time '#{start_time}:00' and  time '#{end_time}:00')
        AND stop_times_lyon.stop_id IN (#{target_stop_ids.map{|s| "'#{s}'"}.join(',')})
        AND stop_times_main.departure_time < stop_times_lyon.departure_time
      ORDER BY stop_times_main.departure_time, stop_times_lyon.arrival_time
    "

    puts sql
    results = ActiveRecord::Base.connection.exec_query(sql)
    tab = {}
    results.each do |result|
      stop_id = tab[result["stop_id"]] ||= {}
      start_time = stop_id[result["start_time"]] ||= {}
      start_time[result["end_time"]] = result["gare_end"]
    end
    tab
  end

  def get_stats_schedule(target_stop_ids, start_time, end_time)
    sql = "

      SELECT  stops.stop_name as gare_start,
              stop_times_main.departure_time::time as start_time,
              stops_lyon.stop_name as gare_end,
              stop_times_lyon.arrival_time::time as end_time,
              stop_times_main.trip_id,
              trips.service_id,
              calendars.monday
      FROM stops
      INNER JOIN stop_times as stop_times_main ON stop_times_main.stop_id = stops.stop_id
      INNER JOIN stop_times as stop_times_lyon ON stop_times_main.trip_id = stop_times_lyon.trip_id
      INNER JOIN stops as stops_lyon ON stop_times_lyon.stop_id = stops_lyon.stop_id
      INNER JOIN trips ON stop_times_main.trip_id = trips.trip_id
      INNER JOIN calendars ON calendars.service_id = trips.service_id
      WHERE stops.stop_id = '#{self.stop_id}'
        AND (stop_times_main.departure_time::time BETWEEN time '#{start_time}:00' and  time '#{end_time}:00')
        AND stop_times_lyon.stop_id IN (#{target_stop_ids.map{|s| "'#{s}'"}.join(',')})
        AND stop_times_main.departure_time < stop_times_lyon.departure_time
      ORDER BY stop_times_main.departure_time, stop_times_lyon.arrival_time
    "
    results = ActiveRecord::Base.connection.exec_query(sql)
    tab = {}
    results.each do |result|
        h = tab[result["start_time"]] || {}
        h[result["end_time"]] = result["gare_end"]
        tab[result["start_time"]] = h
    end
    tab
  end

end

app/models/stop_time.rb
class StopTime < ApplicationRecord
  self.primary_keys = [:stop_id, :trip_id]
  belongs_to :stop
end

app/models/trip.rb
class Trip < ApplicationRecord
  self.primary_key = :trip_id
  has_many  :stop_times
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :start_time
  before_action :end_time
  before_action :range

  DEFAULT_RANGE = 90

  COLORS = {
   "0"    =>  "FFFFFF",
   "1"    =>  "c42525",
   "2"    =>  "c47725",
   "3"    =>  "c4be25",
   "4"    =>  "91c425",
   "more" =>  "5ac425"
  }

  def show
    @stops = Stop.near(city, 4)
  end

  def search
    redirect_to city_path(params[:city])
  end

  def data
    stops = Stop.near(city, range).where.not(stop_id: stop_ids)
    all_stats = Stop.get_many_stats_schedule(stops.map(&:stop_id), stop_ids, start_time, end_time)

    ret = stops.to_a.map do |stop|
      stats = all_stats[stop.stop_id] || []
      nb_trains = stats.size
      color = nb_trains > 4 ? "more" : nb_trains.to_s
      backcolor = nb_trains.zero? ? "000000" : "FFFFFF"

      stop.attributes.merge(
        trips_count: stats.size,
        stats: stats,
        icon_url: "http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=#{URI::encode(nb_trains.to_s)}|#{COLORS[color]}|#{backcolor}",
        html: render_to_string(partial: "/stops/stats.html", locals: { name: stop.stop_name, stats: stats })
      )
    end
    render json: ret
  end

  private

  def city
    @city ||= params[:id]
  end

  def stop_ids
    params[:stop_ids]
  end

  def range
    @range ||= (params[:range] || DEFAULT_RANGE).to_i
  end

  def start_time
    @start_time ||= (params[:start_time] || "07:30")
  end

  def end_time
    @end_time ||= (params[:end_time] || "08:30")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  COLORS = {
   "0"    =>  "000000",
   "1"    =>  "c42525",
   "2"    =>  "c47725",
   "3"    =>  "c4be25",
   "4"    =>  "91c425",
   "more" =>  "5ac425"
  }

  def city
    ap "je sui sla"
  end

  def results


    stops = Stop.near(params[:city], 80).where.not(stop_id: stop_ids)

    ap stops.class


    all_stats = Stop.get_many_stats_schedule(stops.map(&:stop_id), stop_ids, start_time, end_time)

    @markers = Gmaps4rails.build_markers(stops) do |stop, marker|

      stats = all_stats[stop.stop_id] || []
      nb_trains = stats.size

      color = nb_trains > 4 ? "more" : nb_trains.to_s

      backcolor = nb_trains == 0 ? "FFFFFF" : "000000"

      marker.lat stop.stop_lat
      marker.lng stop.stop_lon
      marker.picture({
        "url" => "http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=#{URI::encode(nb_trains.to_s)}|#{COLORS[color]}|#{backcolor}",
        "width" => 21,
        "height" => 34
      })
      marker.infowindow render_to_string(partial: "/stops/stats", locals: { name: stop.stop_name, stats: stats })
    end
  end

  def select_stations
    @stops = Stop.near(params[:city], 4)
    ap @stops
  end

  def home

  end

  private

  def start_time
    @start_time ||= (params[:time] && !params[:time][:start].blank?) ? params[:time][:start] : "07:30"
  end

  def end_time
    @end_time ||= (params[:time] && !params[:time][:end].blank?) ? params[:time][:end] : "08:30"
  end

  def stop_ids
    @stop_ids ||= params[:stop_ids]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cities/show.html.erb
<div class="main-container">
  <div id="map" style="width: 100%; height: 100vh" data-city="<%= @city %>" data-api-key="<%= ENV['MAPBOX_API_FRONT'] %>"></div>

  <div class="sidebar">


    <h1><%= @city %></h1>
    <hr>
    <form id="form" action="">
      <% @stops.each do |stop| %>

        <label >
          <input name="stop_ids[]" type="checkbox" value="<%= stop.stop_id %>" checked> <%= stop.stop_name.gsub(/Gare de /, "") %>
        </label>

        <br>


      <% end %>
      <hr>
      <p>Partir entre</p>

      <input type="radio" name="toto" value="1">
      <input type="radio" name="toto" value="2">
      <input type="radio" name="toto" value="3">

      <div class="hours">
        <input name="start_time"  type="time" step="1800" value="<%= @start_time %>">
        <input name="end_time"    type="time" step="1800" value="<%= @end_time %>">
      </div>
    </form>

    <%= link_to root_path  do %>
      <h3><i class="fas fa-train"></i> TerMap <i class="fas fa-train"></i></h3>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Findhouse</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.4.0/mapbox-gl.css' rel='stylesheet' />
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home">

  <h1>TerMap</h1>

  <p>Cherchez les gares les mieux connectées à une métropole</p>

  <%= form_tag(search_cities_path, method: "get") do %>
    <%= text_field_tag :city, "", placeholder: "Rentrez une ville" %>
  <% end %>

  <div class="cities-card">
    <%= link_to city_path("nantes"), class: 'city-card city-card--nantes'  do %>
      Nantes
    <% end %>


    <%= link_to city_path("lyon"), class: 'city-card city-card--lyon'  do %>
      Lyon
    <% end %>


    <%= link_to city_path("toulouse"), class: 'city-card city-card--toulouse'  do %>
      Toulouse
    <% end %>
  </div>

</div>

app/views/pages/results.html.erb
  <div id="home">
      <div class="map-container">
       <!-- <div id="map" style="width: 100%; height: 100%"></div> -->
       <div id='map' style='width: 400px; height: 300px;'></div>

      </div>
      <div class="form-container">


        <%= form_tag(results_path, method: "get") do %>
          <div class="form-row">
            <div class="col">
              <div class="form-group">
                <%= time_field 'time', 'start', {minute_step: 15, value: @start_time, class: 'form-control', required: true} %>
              </div>
            </div>
            <div class="col">
              <div class="form-group">
                <%= time_field 'time', 'end', {minute_step: 15, value: @end_time, class: 'form-control', required: true} %>
              </div>
            </div>
          </div>

          <%= submit_tag("C'est parti!", class: 'btn btn-primary btn-block') %>
        <% end %>
      </div>
  </div>

</div>

<hr>

app/views/pages/select_stations.html.erb
<h1>select_stations!</h1>


<%= form_tag(results_path, method: "get") do %>
  <%= hidden_field_tag 'city', params[:city] %>
  <% @stops.each do |stop| %>
    <label for="">
      <%= check_box_tag 'stop_ids[]', stop.stop_id, checked: true %>
      <%= stop.stop_name %>
    </label>
    <br>
  <% end %>
  <br>
  <%= submit_tag %>
<% end %>

app/views/stops/_stats.html.erb
<h3><%= name.gsub(/Gare de /, "") %></h3>

<ul>
    <% stats.each do |start_time, end_times| %>
      <li>
        <strong><%= start_time %></strong>
        <ul>
          <% end_times.each do |end_time, end_name| %>
            <li><%= end_time %> : <%= end_name %> (<%= (Time.parse(end_time) - Time.parse(start_time)).to_i / 60 %> min)</li>
          <% end %>
        </ul>
      </li>
    <% end %>
</ul>